<a href="https://colab.research.google.com/github/amonguscline/ML-Data-analysis/blob/main/projects/California_Housing_with_Decision_Trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
test=pd.read_csv("/content/sample_data/california_housing_test.csv")
test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]
model = DecisionTreeRegressor(max_depth=7,min_samples_leaf=8)
model.fit(X,y)
#using the built in test csv from google colab
test_X=test.iloc[:,:-1]
test_y=test.iloc[:,-1]
model.score(test_X,test_y)

0.6464589250142603

In [ ]:
model.predict(X.iloc[0:10,:])

array([ 64027.45098039,  64027.45098039,  64027.45098039, 167432.12560386,
        64027.45098039, 167432.12560386,  89637.70491803,  62405.81162791,
        64027.45098039,  62405.81162791])

In [ ]:
df.head(1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0

In [ ]:
model.predict([[0,	0,	0,	0,	0,	0,	0,	0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([64027.45098039])

I'm getting a problem where no matter how much I try to tweak the model, it's still overfitting like crazy, and no matter how much I change the values to get a different predicted value, it doesn't work. I don't think that decision trees are a good model for my dataset, but I'm not really sure why